#!/bin/bash
# 
# Feature Calculation Step
#

echo "This package demnonstrates that fminer2 and C++ Lazar can reproduce KDD 2009 paper results."

# FMINER
if [ ! -e fminer2/fminer/fminer ]; then
  if [ ! -d fminer2 ]; then
    echo "Checking out fminer2..."
    git clone git://github.com/amaunz/fminer2 > /dev/null
  else
    cd fminer2/; git pull > /dev/null ; cd -
  fi
  cd fminer2/; bash build_all.sh
  if [ $? -gt 0 ]; then
    exit 1
  fi
  cd -
fi

if [ -e fminer2/fminer/fminer ]; then
  FMINER2_DIR=$(pwd)/fminer2
else
  echo "Fminer mot found. Aborting..."
  exit
fi

# LAZAR
if [ ! -d lazar-core ]; then
  echo "Checking out LAZAR..."
  git clone git://github.com/amaunz/lazar-core > /dev/null
fi
echo "Configuring LAZAR..."
cd lazar-core; bash configure >> build.log 2>&1
cd -
echo "Building LAZAR..."
make -C lazar-core lazar >> build.log 2>&1
if [ $? -gt 0 ]; then
  echo "Build failed. Please examine the file 'build.log'."
  exit 1
fi

if [ -e lazar-core/lazar ]; then
  LAZAR_DIR=$(pwd)/lazar-core
else
  echo "Lazar not found. Aborting..."
  exit
fi

# CPDB
if [ ! -d cpdbdata ]; then
  echo "Checking out datasets..."
  git clone git://github.com/amaunz/cpdbdata > /dev/null
fi


FMINER="$FMINER2_DIR/fminer/fminer $FMINER2_DIR/libbbrc/libbbrc.so"
LAZAR="$LAZAR_DIR/lazar"
L2S="$LAZAR_DIR/loo2summary.rb"

MOC="$(pwd)/cpdbdata/mouse_carcinogenicity/mouse_carcinogenicity_alt"
MUC="$(pwd)/cpdbdata/multi_cell_call/multi_cell_call_alt"
SM="$(pwd)/cpdbdata/salmonella_mutagenicity/salmonella_mutagenicity_alt"
RC="$(pwd)/cpdbdata/rat_carcinogenicity/rat_carcinogenicity_alt"

echo "Running leave-one-out Crossvalidations..."
for t in "$MOC" "$MUC" "$SM" "$RC"; do
  fn=$(echo $t | sed 's/.*\///g')
  echo $fn

  export FMINER_LAZAR=1
  export FMINER_SMARTS=1
  echo "  Feature Generation..."
  $FMINER -f6 -a "$t.smi" "$t.class" > "$fn.linfrag" 2>/dev/null
  echo "  Run Crossvalidation..."
  $LAZAR -s "$t.smi" -t "$t.class" -f "$fn.linfrag" -x > "$fn.loo" 2>/dev/null
  $L2S "$fn.loo" "$fn.summary" "$fn" >/dev/null 2>&1

done
